<?php

if ( ! defined( 'ABSPATH' ) ) exit;

if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_gigapixel-slide',
		'title' => 'Gigapixel Slide',
		'fields' => array (
			array (
				'key' => 'field_55e42a258ca94',
				'label' => 'Date',
				'name' => 'gps_date',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_55e42a308ca95',
				'label' => 'Media External Content',
				'name' => 'gps_media_external_content',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_55e42a428ca96',
				'label' => 'Media Image',
				'name' => 'gps_media_image',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_55e42a558ca97',
				'label' => 'Media Caption',
				'name' => 'gps_media_caption',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_55e42a638ca98',
				'label' => 'Media Credit',
				'name' => 'gps_media_credit',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_55e42a6e8ca99',
				'label' => 'Overview Slide?',
				'name' => 'gps_overview_slide',
				'type' => 'true_false',
				'message' => '',
				'default_value' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'gigapixel-slide',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_gigapixel-storymap',
		'title' => 'Gigapixel Storymap',
		'fields' => array (
			array (
				'key' => 'field_55e42a95c1b60',
				'label' => 'Width',
				'name' => 'gpsm_width',
				'type' => 'number',
				'instructions' => 'Value must be numeric only',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_55e42ad3c1b61',
				'label' => 'Height',
				'name' => 'gpsm_height',
				'type' => 'number',
				'instructions' => 'Value must be numeric only',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_55e42ae108160',
				'label' => 'Language',
				'name' => 'gpsm_language',
				'type' => 'select',
				'choices' => array (
					'en' => 'en',
					'be' => 'be',
					'de' => 'de',
					'es' => 'es',
					'fr' => 'fr',
					'he' => 'he',
					'it' => 'it',
					'jp' => 'jp',
					'nl' => 'nl',
					'no' => 'no',
					'pl' => 'pl',
					'sr' => 'sr',
					'sv' => 'sv',
					'zh-cn' => 'zh-cn',
					'zh-tw' => 'zh-tw',
				),
				'default_value' => 'en',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_55e42af708161',
				'label' => 'Font',
				'name' => 'gpsm_font',
				'type' => 'select',
				'choices' => array (
					'default' => 'default',
					'abril-droidsans' => 'abril-droidsans',
					'amatic-andika' => 'amatic-andika',
					'bitter-raleway' => 'bitter-raleway',
					'clicker-garamond' => 'clicker-garamond',
					'dancing-ledger' => 'dancing-ledger',
					'emoji' => 'emoji',
					'fjalla-average' => 'fjalla-average',
					'georgia-helvetica' => 'georgia-helvetica',
					'knightlab' => 'knightlab',
					'lustria-lato' => 'lustria-lato',
					'medula-lato' => 'medula-lato',
					'oldstandard' => 'oldstandard',
					'opensans-gentiumbook' => 'opensans-gentiumbook',
					'playfair-faunaone' => 'playfair-faunaone',
					'playfair' => 'playfair',
					'pt' => 'pt',
					'roboto-megrim' => 'roboto-megrim',
					'rufina-sintony' => 'rufina-sintony',
					'ubuntu' => 'ubuntu',
					'unicaone-vollkorn' => 'unicaone-vollkorn',
				),
				'default_value' => 'default',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_55e42b1308162',
				'label' => 'Calculate Zoom',
				'name' => 'gpsm_calculate_zoom',
				'type' => 'true_false',
				'message' => '',
				'default_value' => 1,
			),
			array (
				'key' => 'field_55e42b2ec2bd2',
				'label' => 'Background Colour',
				'name' => 'gpsm_background_colour',
				'type' => 'color_picker',
				'default_value' => '',
			),
			array (
				'key' => 'field_55e42b4dc2bd3',
				'label' => 'Map as Image',
				'name' => 'gpsm_map_as_image',
				'type' => 'true_false',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_55e42b62c2bd4',
				'label' => 'Gigapixel Slides',
				'name' => 'gpsm_storymap_slides',
				'type' => 'relationship',
				'return_format' => 'object',
				'post_type' => array (
					0 => 'gigapixel-slide',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'filters' => array (
					0 => 'search',
				),
				'result_elements' => array (
					0 => 'post_title',
				),
				'max' => '',
			),
			array (
				'key' => 'field_55e42b87c2bd5',
				'label' => 'Zoomify URL Path',
				'name' => 'gpsm_gigapixel_url_path',
				'type' => 'text',
				'instructions' => 'URL path to zoomable image folder',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'gigapixel-storymap',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_storymap',
		'title' => 'Storymap',
		'fields' => array (
			array (
				'key' => 'field_55e229de439ec',
				'label' => 'Width',
				'name' => 'sm_width',
				'type' => 'text',
				'instructions' => 'Value must end in \'px\' or \'%\'	eg. 800px or 100%',
				'default_value' => '800px',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_55e229fa439ed',
				'label' => 'Height',
				'name' => 'sm_height',
				'type' => 'text',
				'instructions' => 'Value must end in \'px\'	eg. 800px',
				'default_value' => '800px',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_55e22a17a06b9',
				'label' => 'Language',
				'name' => 'sm_language',
				'type' => 'select',
				'choices' => array (
					'en' => 'en',
					'be' => 'be',
					'de' => 'de',
					'es' => 'es',
					'fr' => 'fr',
					'he' => 'he',
					'it' => 'it',
					'jp' => 'jp',
					'nl' => 'nl',
					'no' => 'no',
					'pl' => 'pl',
					'sr' => 'sr',
					'sv' => 'sv',
					'zh-cn' => 'zh-cn',
					'zh-tw' => 'zh-tw',
				),
				'default_value' => 'en',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_55e22a34bdb1f',
				'label' => 'Font',
				'name' => 'sm_font',
				'type' => 'select',
				'choices' => array (
					'default' => 'default',
					'abril-droidsans' => 'abril-droidsans',
					'amatic-andika' => 'amatic-andika',
					'bitter-raleway' => 'bitter-raleway',
					'clicker-garamond' => 'clicker-garamond',
					'dancing-ledger' => 'dancing-ledger',
					'emoji' => 'emoji',
					'fjalla-average' => 'fjalla-average',
					'georgia-helvetica' => 'georgia-helvetica',
					'knightlab' => 'knightlab',
					'lustria-lato' => 'lustria-lato',
					'medula-lato' => 'medula-lato',
					'oldstandard' => 'oldstandard',
					'opensans-gentiumbook' => 'opensans-gentiumbook',
					'playfair-faunaone' => 'playfair-faunaone',
					'playfair' => 'playfair',
					'pt' => 'pt',
					'roboto-megrim' => 'roboto-megrim',
					'rufina-sintony' => 'rufina-sintony',
					'ubuntu' => 'ubuntu',
					'unicaone-vollkorn' => 'unicaone-vollkorn',
				),
				'default_value' => 'default',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_55e22a4ce07bc',
				'label' => 'Calculate Zoom',
				'name' => 'sm_calculate_zoom',
				'type' => 'true_false',
				'message' => '',
				'default_value' => 1,
			),
			array (
				'key' => 'field_55e22ac1e07bd',
				'label' => 'Map Type',
				'name' => 'sm_map_type',
				'type' => 'select',
				'choices' => array (
					'stamen:toner-lite' => 'stamen:toner-lite',
					'stamen:toner' => 'stamen:toner',
					'stamen:toner-lines' => 'stamen:toner-lines',
					'stamen:toner-labels' => 'stamen:toner-labels',
					'stamen:terrain' => 'stamen:terrain',
					'stamen:watercolor' => 'stamen:watercolor',
					'osm:standard' => 'osm:standard',
					'mapbox:map-id' => 'mapbox:map-id',
				),
				'default_value' => 'stamen:toner-lite',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_55e22ae4bfc2b',
				'label' => 'Map ID',
				'name' => 'sm_mapbox_map_id',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_55e22ac1e07bd',
							'operator' => '==',
							'value' => 'stamen',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_55e22b39504b5',
				'label' => 'Map as Image',
				'name' => 'sm_map_as_image',
				'type' => 'true_false',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_55e22b55504b6',
				'label' => 'Storymap Slides',
				'name' => 'sm_storymap_slides',
				'type' => 'relationship',
				'return_format' => 'object',
				'post_type' => array (
					0 => 'storymap-slide',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'filters' => array (
					0 => 'search',
				),
				'result_elements' => array (
					0 => 'post_title',
				),
				'max' => '',
			),
			array (
				'key' => 'field_55e2c508d764f',
				'label' => 'Background Colour',
				'name' => 'sm_background_colour',
				'type' => 'color_picker',
				'default_value' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'storymap',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_storymap-slide',
		'title' => 'Storymap Slide',
		'fields' => array (
			array (
				'key' => 'field_55e22bc13a0a8',
				'label' => 'Date',
				'name' => 'sms_date',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_55e22bd765b59',
				'label' => 'Media External Content',
				'name' => 'sms_media_external_content',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_55e22be865b5a',
				'label' => 'Media Image',
				'name' => 'sms_media_image',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_55e22bfb65b5b',
				'label' => 'Media Caption',
				'name' => 'sms_media_caption',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_55e22c0b65b5c',
				'label' => 'Media Credit',
				'name' => 'sms_media_credit',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_55e22c1a65b5d',
				'label' => 'Overview Slide?',
				'name' => 'sms_overview_slide',
				'type' => 'true_false',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_55e22c2565b5e',
				'label' => 'Location',
				'name' => 'sms_location',
				'type' => 'google_map',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_55e22c1a65b5d',
							'operator' => '!=',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'center_lat' => '',
				'center_lng' => '',
				'zoom' => '',
				'height' => '',
			),
			array (
				'key' => 'field_55e22c3ecc4f1',
				'label' => 'Location Name',
				'name' => 'sms_location_name',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_55e22c1a65b5d',
							'operator' => '!=',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_55e22c4ccc4f2',
				'label' => 'Zoom Level',
				'name' => 'sms_zoom_level',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_55e22c1a65b5d',
							'operator' => '!=',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => 14,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'storymap-slide',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_storymap-slide-category',
		'title' => 'Storymap Slide Category',
		'fields' => array (
			array (
				'key' => 'field_55e22c8b62941',
				'label' => 'Width',
				'name' => 'smsc_width',
				'type' => 'text',
				'instructions' => 'Value must end in \'px\' or \'%\'	eg. 800px or 100%',
				'default_value' => '800px',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_55e22cb462942',
				'label' => 'Height',
				'name' => 'smsc_height',
				'type' => 'text',
				'instructions' => 'Value must end in \'px\'	eg. 800px',
				'default_value' => '800px',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_55e22cc062943',
				'label' => 'Language',
				'name' => 'smsc_language',
				'type' => 'select',
				'choices' => array (
					'en' => 'en',
					'be' => 'be',
					'de' => 'de',
					'es' => 'es',
					'fr' => 'fr',
					'he' => 'he',
					'it' => 'it',
					'jp' => 'jp',
					'nl' => 'nl',
					'no' => 'no',
					'pl' => 'pl',
					'sr' => 'sr',
					'sv' => 'sv',
					'zh-cn' => 'zh-cn',
					'zh-tw' => 'zh-tw',
				),
				'default_value' => 'en',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_55e22ce25337f',
				'label' => 'Font',
				'name' => 'smsc_font',
				'type' => 'select',
				'choices' => array (
					'default' => 'default',
					'abril-droidsans' => 'abril-droidsans',
					'amatic-andika' => 'amatic-andika',
					'bitter-raleway' => 'bitter-raleway',
					'clicker-garamond' => 'clicker-garamond',
					'dancing-ledger' => 'dancing-ledger',
					'emoji' => 'emoji',
					'fjalla-average' => 'fjalla-average',
					'georgia-helvetica' => 'georgia-helvetica',
					'knightlab' => 'knightlab',
					'lustria-lato' => 'lustria-lato',
					'medula-lato' => 'medula-lato',
					'oldstandard' => 'oldstandard',
					'opensans-gentiumbook' => 'opensans-gentiumbook',
					'playfair-faunaone' => 'playfair-faunaone',
					'playfair' => 'playfair',
					'pt' => 'pt',
					'roboto-megrim' => 'roboto-megrim',
					'rufina-sintony' => 'rufina-sintony',
					'ubuntu' => 'ubuntu',
					'unicaone-vollkorn' => 'unicaone-vollkorn',
				),
				'default_value' => 'default',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_55e22cff53380',
				'label' => 'Calculate Zoom',
				'name' => 'smsc_calculate_zoom',
				'type' => 'true_false',
				'message' => '',
				'default_value' => 1,
			),
			array (
				'key' => 'field_55e22d1953381',
				'label' => 'Map Type',
				'name' => 'smsc_map_type',
				'type' => 'select',
				'choices' => array (
					'stamen:toner-lite' => 'stamen:toner-lite',
					'stamen:toner' => 'stamen:toner',
					'stamen:toner-lines' => 'stamen:toner-lines',
					'stamen:toner-labels' => 'stamen:toner-labels',
					'stamen:terrain' => 'stamen:terrain',
					'stamen:watercolor' => 'stamen:watercolor',
					'osm:standard' => 'osm:standard',
					'mapbox:map-id' => 'mapbox:map-id',
				),
				'default_value' => 'stamen:toner-lite',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_55e22d3353382',
				'label' => 'Map ID',
				'name' => 'smsc_mapbox_map_id',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_55e22d1953381',
							'operator' => '==',
							'value' => 'mapbox',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_55e22d5c3fae7',
				'label' => 'Map as Image',
				'name' => 'smsc_map_as_image',
				'type' => 'true_false',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_55e2c54ee241e',
				'label' => 'Background Colour',
				'name' => 'smsc_background_colour',
				'type' => 'color_picker',
				'default_value' => '',
			),
			array (
				'key' => 'field_55e2c11e850c9',
				'label' => 'Optional Category Cover Slide',
				'name' => 'smsc_optional_category_cover_slide',
				'type' => 'true_false',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_55e2c235850ce',
				'label' => 'Cover Slide Media External Content',
				'name' => 'smsc_cover_slide_media_external_content',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_55e2c11e850c9',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_55e2c1ce850cc',
				'label' => 'Cover Slide Media Image',
				'name' => 'smsc_cover_slide_media_image',
				'type' => 'image',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_55e2c11e850c9',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_55e2c1ff850cd',
				'label' => 'Cover Slide Media Caption',
				'name' => 'smsc_cover_slide_media_caption',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_55e2c11e850c9',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_55e2c3e91ac9f',
				'label' => 'Cover Slide Media Credit',
				'name' => 'smsc_cover_slide_media_credit',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_55e2c11e850c9',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'ef_taxonomy',
					'operator' => '==',
					'value' => 'slide-category',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}



?>